// Language system - Norwegian (no) and English (en)
const LANG = {
  en: {
    appName: 'Greenkeeper',
    tasks: 'Tasks',
    map: 'Map',
    settings: 'Settings',
    addTask: 'Add',
    taskPlaceholder: 'Add new task...',
    completed: 'Completed',
    deleteConfirm: 'Are you sure you want to delete this?',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    noTasks: 'No tasks yet',
    // Map
    locateMe: 'Locate me',
    addInfrastructure: 'Add Infrastructure',
    infrastructureType: 'Type',
    description: 'Description',
    takePhoto: 'Take Photo / Upload',
    droneOverlay: 'Drone Overlay',
    droneToggle: 'Toggle drone overlay',
    // Satellite
    satelliteView: 'Satellite View',
    toggleSatellite: 'Toggle satellite view',
    // Pin mode
    pinMode: 'PIN',
    pinModeOn: 'Pin mode ON — tap map to drop pins',
    pinModeOff: 'Pin mode OFF',
    // Infrastructure types
    drain: 'Drain',
    electricalOutlet: 'Electrical Outlet',
    wateringSystem: 'Watering System',
    sprinklerHead: 'Sprinkler Head',
    valveBox: 'Valve Box',
    // Settings
    language: 'Language',
    droneImage: 'Drone Image',
    uploadDrone: 'Upload drone image',
    tapToUploadDrone: 'Tap to upload drone / satellite image',
    droneFormats: 'JPG, PNG, TIFF supported',
    setBounds: 'Set Map Bounds',
    swCorner: 'SW Corner (stand there & tap)',
    neCorner: 'NE Corner (stand there & tap)',
    setFromGPS: 'Set from GPS',
    firebaseStatus: 'Firebase Status',
    connected: 'Connected',
    notConnected: 'Not connected - using local storage',
    configureFirebase: 'Configure Firebase',
    clearData: 'Clear All Data',
    clearConfirm: 'This will delete all local data. Are you sure?',
    about: 'About',
    version: 'Version',
    // Infrastructure modal
    addedOn: 'Added on',
    coordinates: 'Coordinates',
    photo: 'Photo',
    noPhoto: 'No photo',
    editNote: 'Edit note...',
    note: 'Note',
    notePlaceholder: 'Add a note...',
    saving: 'Saving...',
    saved: 'Saved',
    gpsWaiting: 'Getting GPS position...',
    gpsError: 'Could not get GPS position',
    selectType: 'Select type...',
    filterAll: 'All',
  },
  no: {
    appName: 'Greenkeeper',
    tasks: 'Oppgaver',
    map: 'Kart',
    settings: 'Innstillinger',
    addTask: 'Legg til',
    taskPlaceholder: 'Legg til ny oppgave...',
    completed: 'Fullført',
    deleteConfirm: 'Er du sikker på at du vil slette dette?',
    delete: 'Slett',
    edit: 'Rediger',
    save: 'Lagre',
    cancel: 'Avbryt',
    noTasks: 'Ingen oppgaver ennå',
    // Map
    locateMe: 'Finn meg',
    addInfrastructure: 'Legg til infrastruktur',
    infrastructureType: 'Type',
    description: 'Beskrivelse',
    takePhoto: 'Ta bilde / Last opp',
    droneOverlay: 'Dronebilde',
    droneToggle: 'Vis/skjul dronebilde',
    // Satellite
    satelliteView: 'Satellittvisning',
    toggleSatellite: 'Vis/skjul satellittbilde',
    // Pin mode
    pinMode: 'PIN',
    pinModeOn: 'Pin-modus PÅ — trykk på kartet for å sette punkt',
    pinModeOff: 'Pin-modus AV',
    // Infrastructure types
    drain: 'Sluk',
    electricalOutlet: 'Strømuttak',
    wateringSystem: 'Vanningsanlegg',
    sprinklerHead: 'Sprinklerhode',
    valveBox: 'Ventilboks',
    // Settings
    language: 'Språk',
    droneImage: 'Dronebilde',
    uploadDrone: 'Last opp dronebilde',
    tapToUploadDrone: 'Trykk for å laste opp drone-/satellittbilde',
    droneFormats: 'JPG, PNG, TIFF støttes',
    setBounds: 'Sett kartgrenser',
    swCorner: 'SV-hjørne (stå der og trykk)',
    neCorner: 'NØ-hjørne (stå der og trykk)',
    setFromGPS: 'Sett fra GPS',
    firebaseStatus: 'Firebase-status',
    connected: 'Tilkoblet',
    notConnected: 'Ikke tilkoblet - bruker lokal lagring',
    configureFirebase: 'Konfigurer Firebase',
    clearData: 'Slett alle data',
    clearConfirm: 'Dette vil slette alle lokale data. Er du sikker?',
    about: 'Om',
    version: 'Versjon',
    // Infrastructure modal
    addedOn: 'Lagt til',
    coordinates: 'Koordinater',
    photo: 'Bilde',
    noPhoto: 'Ingen bilde',
    editNote: 'Rediger notat...',
    note: 'Notat',
    notePlaceholder: 'Legg til et notat...',
    saving: 'Lagrer...',
    saved: 'Lagret',
    gpsWaiting: 'Henter GPS-posisjon...',
    gpsError: 'Kunne ikke hente GPS-posisjon',
    selectType: 'Velg type...',
    filterAll: 'Alle',
  }
};

// Infrastructure type definitions with icons and colors
const INFRA_TYPES = {
  drain:           { icon: '🔵', color: '#2196F3', emoji: '🕳️' },
  electricalOutlet:{ icon: '⚡', color: '#FF9800', emoji: '⚡' },
  wateringSystem:  { icon: '💧', color: '#00BCD4', emoji: '💧' },
  sprinklerHead:   { icon: '🟢', color: '#4CAF50', emoji: '⛲' },
  valveBox:        { icon: '🔴', color: '#F44336', emoji: '🔧' },
};
